In [1]:
import pandas as pd

In [96]:
df=pd.read_csv("/content/IMDB Dataset.csv",engine="python")

In [97]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

**Lowering Text**

In [98]:
df["review"]=df["review"].str.lower()

**Remove Unimportant Things (Htmltags etc)**

In [99]:
import re

In [100]:
def remove_tags(text):
  patterns=re.compile('<.*?>')
  return patterns.sub(r'',text)

In [101]:
df["review"]=df["review"].apply(remove_tags)

In [102]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

**Remove URLS**

In [103]:
def remove_url(text):
  patterns=re.compile(r'https?://|S+|www\.\S+')
  return  patterns.sub(r'',text)

In [104]:
df["review"]=df["review"].apply(remove_url)

In [105]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

**Remove Punctuations**

In [107]:
import string

In [108]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [109]:
exclude=string.punctuation

In [110]:
def remove_punctuation(text):
  for char in exclude:
    text=text.replace(char,"")
  return text

In [111]:
df["review"]=df["review"].apply(remove_punctuation)

In [112]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

**Tokenization**

In [113]:
from nltk.tokenize import word_tokenize

In [114]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [115]:
tokenized=df["review"].apply(word_tokenize)

In [116]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [127]:
tokenized

0        [one, of, the, other, reviewers, has, mentione...
1        [a, wonderful, little, production, the, filmin...
2        [i, thought, this, was, a, wonderful, way, to,...
3        [basically, theres, a, family, where, a, littl...
4        [petter, matteis, love, in, the, time, of, mon...
                               ...
49995    [i, thought, this, movie, did, a, down, right,...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [i, am, a, catholic, taught, in, parochial, el...
49998    [im, going, to, have, to, disagree, with, the,...
49999    [no, one, expects, the, star, trek, movies, to...
Name: review, Length: 50000, dtype: object

In [90]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 76.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [91]:
from gensim.models import Word2Vec

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [128]:
word_vec=Word2Vec(
    sentences=tokenized,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

In [130]:

tokenizer = Tokenizer()

tokenizer.fit_on_texts(tokenized)

sequences = tokenizer.texts_to_sequences(tokenized)

word_index = tokenizer.word_index

In [132]:
word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'in': 7,
 'it': 8,
 'i': 9,
 'this': 10,
 'that': 11,
 'was': 12,
 'as': 13,
 'with': 14,
 'for': 15,
 'movie': 16,
 'but': 17,
 'film': 18,
 'on': 19,
 'not': 20,
 'you': 21,
 'are': 22,
 'his': 23,
 'have': 24,
 'be': 25,
 'he': 26,
 'one': 27,
 'its': 28,
 'at': 29,
 'all': 30,
 'by': 31,
 'an': 32,
 'they': 33,
 'who': 34,
 'from': 35,
 'like': 36,
 'so': 37,
 'or': 38,
 'just': 39,
 'her': 40,
 'about': 41,
 'has': 42,
 'out': 43,
 'if': 44,
 'some': 45,
 'what': 46,
 'there': 47,
 'good': 48,
 'more': 49,
 'very': 50,
 'when': 51,
 'even': 52,
 'up': 53,
 'no': 54,
 'my': 55,
 'would': 56,
 'can': 57,
 'she': 58,
 'time': 59,
 'only': 60,
 'which': 61,
 'really': 62,
 'their': 63,
 'see': 64,
 'were': 65,
 'story': 66,
 'had': 67,
 'me': 68,
 'than': 69,
 'much': 70,
 'we': 71,
 'well': 72,
 'been': 73,
 'get': 74,
 'will': 75,
 'into': 76,
 'other': 77,
 'great': 78,
 'do': 79,
 'bad': 80,
 'because': 81,
 'also': 82,
 'people': 83,
 'how': 84,
 'most': 85,
 'him': 86,
 'first': 87,
 'dont': 88,
 'movies': 89,
 'made': 90,
 'then': 91,
 'them': 92,
 'make': 93,
 'films': 94,
 'could': 95,
 'way': 96,
 'any': 97,
 'too': 98,
 'characters': 99,
 'after': 100,
 'think': 101,
 'watch': 102,
 'many': 103,
 'seen': 104,
 'being': 105,
 'two': 106,
 'character': 107,
 'never': 108,
 'love': 109,
 'acting': 110,
 'did': 111,
 'where': 112,
 'little': 113,
 'plot': 114,
 'best': 115,
 'know': 116,
 'show': 117,
 'life': 118,
 'ever': 119,
 'does': 120,
 'your': 121,
 'better': 122,
 'off': 123,
 'say': 124,
 'over': 125,
 'still': 126,
 'these': 127,
 'scene': 128,
 'end': 129,
 'man': 130,
 'scenes': 131,
 'why': 132,
 'here': 133,
 'such': 134,
 'while': 135,
 'something': 136,
 'go': 137,
 'should': 138,
 'through': 139,
 'those': 140,
 'back': 141,
 'real': 142,
 'im': 143,
 'watching': 144,
 'thing': 145,
 'doesnt': 146,
 'didnt': 147,
 'actors': 148,
 'years': 149,
 'now': 150,
 'actually': 151,
 'though': 152,
 'funny': 153,
 'makes': 154,
 'before': 155,
 'another': 156,
 'find': 157,
 'nothing': 158,
 'look': 159,
 'going': 160,
 'same': 161,
 'work': 162,
 'lot': 163,
 'new': 164,
 'few': 165,
 'every': 166,
 'old': 167,
 'us': 168,
 'part': 169,
 'cant': 170,
 'again': 171,
 'director': 172,
 'want': 173,
 'quite': 174,
 'thats': 175,
 'got': 176,
 'things': 177,
 'pretty': 178,
 'cast': 179,
 'seems': 180,
 'around': 181,
 'young': 182,
 'down': 183,
 'take': 184,
 'fact': 185,
 'world': 186,
 'enough': 187,
 'big': 188,
 'both': 189,
 'horror': 190,
 'thought': 191,
 'give': 192,
 'may': 193,
 'between': 194,
 'own': 195,
 'ive': 196,
 'however': 197,
 'without': 198,
 'long': 199,
 'saw': 200,
 'isnt': 201,
 'always': 202,
 'gets': 203,
 'right': 204,
 'music': 205,
 'original': 206,
 'must': 207,
 'almost': 208,
 'come': 209,
 'series': 210,
 'times': 211,
 'comedy': 212,
 'whole': 213,
 'role': 214,
 'least': 215,
 'interesting': 216,
 'guy': 217,
 'action': 218,
 'point': 219,
 'bit': 220,
 'theres': 221,
 'done': 222,
 'far': 223,
 'might': 224,
 'am': 225,
 'hes': 226,
 'minutes': 227,
 'script': 228,
 'feel': 229,
 'anything': 230,
 'last': 231,
 'since': 232,
 'probably': 233,
 'family': 234,
 'kind': 235,
 'performance': 236,
 'tv': 237,
 'away': 238,
 'rather': 239,
 'yet': 240,
 'worst': 241,
 'each': 242,
 'fun': 243,
 'found': 244,
 'anyone': 245,
 'sure': 246,
 'played': 247,
 'girl': 248,
 'making': 249,
 'our': 250,
 'believe': 251,
 'woman': 252,
 'trying': 253,
 'shows': 254,
 'especially': 255,
 'having': 256,
 'course': 257,
 'comes': 258,
 'hard': 259,
 'goes': 260,
 'day': 261,
 'put': 262,
 'although': 263,
 'everything': 264,
 'different': 265,
 'worth': 266,
 'main': 267,
 'looking': 268,
 'dvd': 269,
 'ending': 270,
 'place': 271,
 'looks': 272,
 'wasnt': 273,
 'book': 274,
 'watched': 275,
 'maybe': 276,
 'sense': 277,
 'reason': 278,
 'once': 279,
 'screen': 280,
 'three': 281,
 'set': 282,
 'effects': 283,
 'someone': 284,
 'true': 285,
 'plays': 286,
 'play': 287,
 'job': 288,
 'money': 289,
 'together': 290,
 'actor': 291,
 'said': 292,
 'during': 293,
 'seem': 294,
 'takes': 295,
 '10': 296,
 '2': 297,
 'american': 298,
 'everyone': 299,
 'instead': 300,
 'beautiful': 301,
 'special': 302,
 'seeing': 303,
 'later': 304,
 'left': 305,
 'audience': 306,
 'himself': 307,
 'war': 308,
 'version': 309,
 'excellent': 310,
 'john': 311,
 'idea': 312,
 'night': 313,
 'shot': 314,
 'black': 315,
 'simply': 316,
 'high': 317,
 'fan': 318,
 'youre': 319,
 'completely': 320,
 'used': 321,
 'house': 322,
 'nice': 323,
 'read': 324,
 'poor': 325,
 'else': 326,
 'wife': 327,
 'death': 328,
 'kids': 329,
 'friends': 330,
 'short': 331,
 'along': 332,
 'help': 333,
 'men': 334,
 'second': 335,
 'mind': 336,
 'use': 337,
 'less': 338,
 'star': 339,
 'home': 340,
 'need': 341,
 'try': 342,
 'half': 343,
 'given': 344,
 'enjoy': 345,
 'year': 346,
 'boring': 347,
 'until': 348,
 'rest': 349,
 'either': 350,
 'classic': 351,
 'truly': 352,
 'performances': 353,
 'recommend': 354,
 'dead': 355,
 'couple': 356,
 'production': 357,
 'wrong': 358,
 'stupid': 359,
 'line': 360,
 'father': 361,
 'hollywood': 362,
 'start': 363,
 'next': 364,
 'tell': 365,
 'came': 366,
 'getting': 367,
 'women': 368,
 'understand': 369,
 'remember': 370,
 'full': 371,
 'let': 372,
 'school': 373,
 'keep': 374,
 'camera': 375,
 'terrible': 376,
 'others': 377,
 'awful': 378,
 'moments': 379,
 'mean': 380,
 'sex': 381,
 'wonderful': 382,
 'playing': 383,
 'perhaps': 384,
 'video': 385,
 'itself': 386,
 'name': 387,
 'human': 388,
 'gives': 389,
 'doing': 390,
 'often': 391,
 'budget': 392,
 'episode': 393,
 'small': 394,
 'couldnt': 395,
 'definitely': 396,
 'perfect': 397,
 'early': 398,
 'person': 399,
 'top': 400,
 'went': 401,
 'lines': 402,
 'dialogue': 403,
 'absolutely': 404,
 'face': 405,
 'piece': 406,
 'guys': 407,
 'certainly': 408,
 'become': 409,
 'liked': 410,
 'stars': 411,
 'case': 412,
 'sort': 413,
 'head': 414,
 'loved': 415,
 'hope': 416,
 'entire': 417,
 'felt': 418,
 'supposed': 419,
 'lost': 420,
 'several': 421,
 'live': 422,
 'style': 423,
 'mother': 424,
 'entertaining': 425,
 'written': 426,
 'worse': 427,
 'picture': 428,
 'against': 429,
 'title': 430,
 'laugh': 431,
 'finally': 432,
 'waste': 433,
 'problem': 434,
 'boy': 435,
 'friend': 436,
 'totally': 437,
 'sound': 438,
 'shes': 439,
 'beginning': 440,
 'seemed': 441,
 'wanted': 442,
 'yes': 443,
 'based': 444,
 'cinema': 445,
 'mr': 446,
 'dark': 447,
 'care': 448,
 'becomes': 449,
 'humor': 450,
 'wont': 451,
 'already': 452,
 'fans': 453,
 'lead': 454,
 'example': 455,
 'guess': 456,
 'youll': 457,
 'final': 458,
 'children': 459,
 'evil': 460,
 'called': 461,
 '3': 462,
 'direction': 463,
 'lives': 464,
 'able': 465,
 'turn': 466,
 'low': 467,
 'id': 468,
 'throughout': 469,
 'game': 470,
 'drama': 471,
 'white': 472,
 'wants': 473,
 'oh': 474,
 'girls': 475,
 'days': 476,
 'fine': 477,
 'despite': 478,
 '\x96': 479,
 'under': 480,
 'quality': 481,
 'horrible': 482,
 'theyre': 483,
 'amazing': 484,
 'writing': 485,
 'history': 486,
 'tries': 487,
 'works': 488,
 'kill': 489,
 'enjoyed': 490,
 'turns': 491,
 'gave': 492,
 'killer': 493,
 'act': 494,
 'unfortunately': 495,
 'michael': 496,
 'son': 497,
 'past': 498,
 'parts': 499,
 'favorite': 500,
 'side': 501,
 'flick': 502,
 'behind': 503,
 'matter': 504,
 'expect': 505,
 'car': 506,
 '1': 507,
 'brilliant': 508,
 'town': 509,
 'eyes': 510,
 'run': 511,
 'starts': 512,
 'ones': 513,
 'stuff': 514,
 'obviously': 515,
 'sometimes': 516,
 'myself': 517,
 'killed': 518,
 'themselves': 519,
 'viewer': 520,
 'says': 521,
 'thinking': 522,
 'took': 523,
 'soon': 524,
 'overall': 525,
 'group': 526,
 'directed': 527,
 'decent': 528,
 'actress': 529,
 'heart': 530,
 'late': 531,
 'art': 532,
 'city': 533,
 'heard': 534,
 'genre': 535,
 'happens': 536,
 'feeling': 537,
 'kid': 538,
 'highly': 539,
 'hell': 540,
 'fight': 541,
 'except': 542,
 'child': 543,
 'extremely': 544,
 'ill': 545,
 'leave': 546,
 'wouldnt': 547,
 'told': 548,
 'lack': 549,
 'blood': 550,
 'close': 551,
 'etc': 552,
 'police': 553,
 'experience': 554,
 'moment': 555,
 'hour': 556,
 'coming': 557,
 'wonder': 558,
 'looked': 559,
 'stories': 560,
 'involved': 561,
 'chance': 562,
 'strong': 563,
 'hand': 564,
 'particularly': 565,
 'type': 566,
 'save': 567,
 'score': 568,
 'daughter': 569,
 'living': 570,
 'including': 571,
 'attempt': 572,
 'complete': 573,
 'shown': 574,
 'serious': 575,
 'taken': 576,
 'simple': 577,
 'obvious': 578,
 'god': 579,
 'roles': 580,
 'happened': 581,
 'hilarious': 582,
 'violence': 583,
 'stop': 584,
 'happen': 585,
 'cool': 586,
 'james': 587,
 'across': 588,
 'murder': 589,
 'voice': 590,
 'known': 591,
 'exactly': 592,
 'song': 593,
 'opening': 594,
 'ago': 595,
 'number': 596,
 'usually': 597,
 'robert': 598,
 'released': 599,
 'slow': 600,
 'saying': 601,
 'huge': 602,
 'david': 603,
 'wish': 604,
 'jokes': 605,
 'ok': 606,
 'reality': 607,
 'interest': 608,
 'whose': 609,
 'order': 610,
 'hours': 611,
 'cinematography': 612,
 'english': 613,
 'crap': 614,
 'relationship': 615,
 'sad': 616,
 'hit': 617,
 'alone': 618,
 'none': 619,
 'lets': 620,
 'running': 621,
 'shots': 622,
 'possible': 623,
 'talent': 624,
 'annoying': 625,
 'seriously': 626,
 'yourself': 627,
 'gore': 628,
 'started': 629,
 'cut': 630,
 'age': 631,
 'major': 632,
 'career': 633,
 'today': 634,
 'call': 635,
 'please': 636,
 'female': 637,
 'brother': 638,
 'somewhat': 639,
 'taking': 640,
 'ends': 641,
 'usual': 642,
 'ridiculous': 643,
 'knew': 644,
 'hero': 645,
 'beyond': 646,
 'mostly': 647,
 'important': 648,
 'change': 649,
 'view': 650,
 'knows': 651,
 'documentary': 652,
 'body': 653,
 'turned': 654,
 'finds': 655,
 'power': 656,
 'opinion': 657,
 'words': 658,
 'silly': 659,
 'word': 660,
 'strange': 661,
 'due': 662,
 'novel': 663,
 '5': 664,
 'husband': 665,
 'scary': 666,
 'anyway': 667,
 'apparently': 668,
 'local': 669,
 'upon': 670,
 'talking': 671,
 'attention': 672,
 'happy': 673,
 'directors': 674,
 'clearly': 675,
 'cheap': 676,
 'episodes': 677,
 'musical': 678,
 'country': 679,
 'arent': 680,
 'four': 681,
 'room': 682,
 'basically': 683,
 'single': 684,
 'level': 685,
 'problems': 686,
 '4': 687,
 'disappointed': 688,
 'television': 689,
 'british': 690,
 'tells': 691,
 'sequence': 692,
 'events': 693,
 'miss': 694,
 'jack': 695,
 'modern': 696,
 'talk': 697,
 'light': 698,
 'songs': 699,
 'whats': 700,
 'french': 701,
 'whether': 702,
 'appears': 703,
 'sets': 704,
 'predictable': 705,
 'bring': 706,
 'easily': 707,
 'giving': 708,
 'havent': 709,
 'review': 710,
 'rating': 711,
 'supporting': 712,
 'add': 713,
 'dialog': 714,
 'mention': 715,
 'falls': 716,
 'lots': 717,
 'similar': 718,
 'soundtrack': 719,
 'needs': 720,
 'viewers': 721,
 'romantic': 722,
 'bunch': 723,
 'team': 724,
 'ten': 725,
 'above': 726,
 'enjoyable': 727,
 'hate': 728,
 'future': 729,
 'showing': 730,
 'george': 731,
 'within': 732,
 'tried': 733,
 'message': 734,
 'five': 735,
 'entertainment': 736,
 'certain': 737,
 'surprised': 738,
 'moving': 739,
 'clear': 740,
 'earth': 741,
 'parents': 742,
 'comic': 743,
 'space': 744,
 'middle': 745,
 'storyline': 746,
 'among': 747,
 'filmed': 748,
 'dull': 749,
 'named': 750,
 'fall': 751,
 'theme': 752,
 'sequel': 753,
 'easy': 754,
 'theater': 755,
 'ways': 756,
 'feels': 757,
 'king': 758,
 'kept': 759,
 'release': 760,
 'typical': 761,
 'near': 762,
 'stay': 763,
 'using': 764,
 'thriller': 765,
 'greatest': 766,
 'buy': 767,
 'comments': 768,
 'gone': 769,
 'doubt': 770,
 'working': 771,
 'effort': 772,
 'nearly': 773,
 'sorry': 774,
 'writer': 775,
 'elements': 776,
 'actual': 777,
 'deal': 778,
 'means': 779,
 'monster': 780,
 'tale': 781,
 'subject': 782,
 'suspense': 783,
 'brought': 784,
 'fantastic': 785,
 '80s': 786,
 'editing': 787,
 'famous': 788,
 'straight': 789,
 'die': 790,
 'boys': 791,
 'lady': 792,
 'herself': 793,
 'realistic': 794,
 'rock': 795,
 'points': 796,
 'dr': 797,
 'general': 798,
 'leads': 799,
 'youve': 800,
 'sister': 801,
 'feature': 802,
 'imagine': 803,
 'peter': 804,
 'viewing': 805,
 'move': 806,
 'class': 807,
 'form': 808,
 'begins': 809,
 'richard': 810,
 'mystery': 811,
 'reviews': 812,
 'somehow': 813,
 'hear': 814,
 'material': 815,
 'check': 816,
 'forget': 817,
 'dog': 818,
 'learn': 819,
 'figure': 820,
 'whos': 821,
 'rent': 822,
 'sit': 823,
 'particular': 824,
 'weak': 825,
 'animation': 826,
 'period': 827,
 'premise': 828,
 'surprise': 829,
 'believable': 830,
 'killing': 831,
 'sequences': 832,
 'expected': 833,
 'decided': 834,
 'eventually': 835,
 'atmosphere': 836,
 'crime': 837,
 'avoid': 838,
 'paul': 839,
 'difficult': 840,
 'wait': 841,
 'york': 842,
 'deep': 843,
 'fast': 844,
 'red': 845,
 'okay': 846,
 'leaves': 847,
 'became': 848,
 'truth': 849,
 'tom': 850,
 'possibly': 851,
 'emotional': 852,
 'average': 853,
 'indeed': 854,
 'poorly': 855,
 'situation': 856,
 'eye': 857,
 'follow': 858,
 'lame': 859,
 'dance': 860,
 'forced': 861,
 'stand': 862,
 'meet': 863,
 'needed': 864,
 'footage': 865,
 'shame': 866,
 'begin': 867,
 'whatever': 868,
 'crew': 869,
 'memorable': 870,
 'scifi': 871,
 'minute': 872,
 'open': 873,
 'oscar': 874,
 'sexual': 875,
 'reading': 876,
 'meets': 877,
 'features': 878,
 'write': 879,
 'season': 880,
 'writers': 881,
 'previous': 882,
 'doctor': 883,
 'filmmakers': 884,
 'question': 885,
 'whom': 886,
 'interested': 887,
 'credits': 888,
 'beauty': 889,
 'romance': 890,
 'cheesy': 891,
 'nor': 892,
 'gay': 893,
 'personal': 894,
 'imdb': 895,
 'hot': 896,
 'keeps': 897,
 'third': 898,
 'unless': 899,
 'superb': 900,
 'nature': 901,
 'total': 902,
 'inside': 903,
 'western': 904,
 'otherwise': 905,
 'hands': 906,
 'society': 907,
 'towards': 908,
 'male': 909,
 'incredibly': 910,
 'perfectly': 911,
 'screenplay': 912,
 'note': 913,
 'box': 914,
 'comment': 915,
 'sounds': 916,
 'weird': 917,
 'de': 918,
 'result': 919,
 'quickly': 920,
 '20': 921,
 'realize': 922,
 'effect': 923,
 'street': 924,
 'japanese': 925,
 'island': 926,
 'battle': 927,
 'laughs': 928,
 'masterpiece': 929,
 'plus': 930,
 'worked': 931,
 'badly': 932,
 'unique': 933,
 'copy': 934,
 'earlier': 935,
 'older': 936,
 'various': 937,
 'crazy': 938,
 'brings': 939,
 'america': 940,
 'air': 941,
 'stage': 942,
 'plenty': 943,
 'background': 944,
 'appear': 945,
 'setting': 946,
 'free': 947,
 'admit': 948,
 'b': 949,
 'ask': 950,
 'fairly': 951,
 'powerful': 952,
 'lee': 953,
 'spent': 954,
 'portrayed': 955,
 'front': 956,
 'leading': 957,
 'business': 958,
 'following': 959,
 'creepy': 960,
 'directing': 961,
 'dramatic': 962,
 'forward': 963,
 'mark': 964,
 'acted': 965,
 'baby': 966,
 'joe': 967,
 'mess': 968,
 'remake': 969,
 'rich': 970,
 'development': 971,
 'pay': 972,
 'dumb': 973,
 'outside': 974,
 'meant': 975,
 'attempts': 976,
 'deserves': 977,
 'manages': 978,
 'political': 979,
 'fire': 980,
 'fails': 981,
 'expecting': 982,
 'water': 983,
 'wasted': 984,
 'bill': 985,
 'joke': 986,
 '70s': 987,
 'create': 988,
 'ideas': 989,
 'caught': 990,
 'la': 991,
 'agree': 992,
 'hardly': 993,
 'cover': 994,
 'reasons': 995,
 'return': 996,
 'missing': 997,
 'fighting': 998,
 'cop': 999,
 'success': 1000,
 ...}

In [134]:
labels=df["sentiment"]

In [136]:
labels=labels.map({"positive":1,"negative":0})

In [137]:
max_len = 100

X = pad_sequences(sequences, maxlen=max_len)
y = labels.values

In [139]:
import numpy as np

In [141]:
embedding_dim = 100
vocab_size = len(word_index) + 1

embedding_matrix = np.zeros((vocab_size, embedding_dim))

In [144]:
for word, i in word_index.items():

    if word in word_vec.wv:
        embedding_matrix[i] = word_vec.wv[word]

In [145]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

from sklearn.model_selection import train_test_split

In [150]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [147]:
model=Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        weights=(embedding_matrix),
        input_length=max_len,
        trainable=False
    )
)
model.add(SimpleRNN(64))

model.add(Dense(1, activation='sigmoid'))

In [148]:

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [156]:
model.fit(
    X_train,
    y_train,
    epochs=16,
    batch_size=32,
    validation_data=(X_test, y_test)
)

Epoch 1/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.6951 - loss: 0.5676 - val_accuracy: 0.7102 - val_loss: 0.5510
Epoch 2/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7382 - loss: 0.5337 - val_accuracy: 0.7550 - val_loss: 0.5186
Epoch 3/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7485 - loss: 0.5246 - val_accuracy: 0.6270 - val_loss: 0.6284
Epoch 4/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7215 - loss: 0.5482 - val_accuracy: 0.7275 - val_loss: 0.5398
Epoch 5/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7597 - loss: 0.5128 - val_accuracy: 0.7595 - val_loss: 0.5138
Epoch 6/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7361 - loss: 0.5313 - val_accuracy: 0.7531 - val_loss: 0.5136
Epoch 7/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7627 - loss: 0.5099 - val_accuracy: 0.6932 - val_loss: 0.5880
Epoch 8/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7361 - loss: 0.5349 - val_accuracy: 0.7165 - val_loss: 0.5455
Epoch 9/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7402 - loss: 0.5281 - val_accuracy: 0.7270 - val_loss: 0.5342
Epoch 10/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7194 - loss: 0.5543 - val_accuracy: 0.6471 - val_loss: 0.6136
Epoch 11/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7116 - loss: 0.5586 - val_accuracy: 0.7213 - val_loss: 0.5536
Epoch 12/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7088 - loss: 0.5624 - val_accuracy: 0.6961 - val_loss: 0.5690
Epoch 13/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7188 - loss: 0.5528 - val_accuracy: 0.6526 - val_loss: 0.6138
Epoch 14/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.6911 - loss: 0.5756 - val_accuracy: 0.7107 - val_loss: 0.5582
Epoch 15/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.6909 - loss: 0.5750 - val_accuracy: 0.7002 - val_loss: 0.5656
Epoch 16/16
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7372 - loss: 0.5258 - val_accuracy: 0.7360 - val_loss: 0.5281

In [157]:

loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7360 - loss: 0.5281
Test Accuracy: 0.7360000014305115

In [161]:
def preprocess(text):
    text = str(text).lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)

    # Remove mentions & hashtags
    text = re.sub(r'\@\w+|\#','', text)

    # Remove punctuation & numbers
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    # Tokenization
    tokens = word_tokenize(text)



    return tokens

In [190]:
def predict_sentiment(text):
    tokens = preprocess(text)
    seq = tokenizer.texts_to_sequences([tokens])
    padded = pad_sequences(seq, maxlen=max_len, padding='post')

    prediction = model.predict(padded)[0][0]

    # Debugging lines
    print(f"Tokens: {tokens}")
    print(f"Raw Score: {prediction}")

    return "Positive" if prediction >= 0.5 else "Negative"

In [191]:
predict_sentiment("this was absolutely amazing and i loved every minute")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Tokens: ['this', 'was', 'absolutely', 'amazing', 'and', 'i', 'loved', 'every', 'minute']
Raw Score: 0.8356509208679199

'Positive'

In [192]:
model.save("sentiment_model.keras")